// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEu8VgoUngcxzQSR6IvtiKG15g2RZUlsQ',
    appId: '1:825243621147:web:8f9845fc94077094b125be',
    messagingSenderId: '825243621147',
    projectId: 'camiones-2027',
    authDomain: 'camiones-2027.firebaseapp.com',
    databaseURL: 'https://camiones-2027-default-rtdb.firebaseio.com',
    storageBucket: 'camiones-2027.firebasestorage.app',
    measurementId: 'G-Z573TRE84T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWQuHQGgKUHFBSZAp8hteBw2s4aTs5qo',
    appId: '1:825243621147:android:3eee7f4474751a40b125be',
    messagingSenderId: '825243621147',
    projectId: 'camiones-2027',
    databaseURL: 'https://camiones-2027-default-rtdb.firebaseio.com',
    storageBucket: 'camiones-2027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7GGA-HrKxPpD_E8r0LZlmA579OjU3NQc',
    appId: '1:825243621147:ios:1493b30f41d4abc4b125be',
    messagingSenderId: '825243621147',
    projectId: 'camiones-2027',
    databaseURL: 'https://camiones-2027-default-rtdb.firebaseio.com',
    storageBucket: 'camiones-2027.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7GGA-HrKxPpD_E8r0LZlmA579OjU3NQc',
    appId: '1:825243621147:ios:1493b30f41d4abc4b125be',
    messagingSenderId: '825243621147',
    projectId: 'camiones-2027',
    databaseURL: 'https://camiones-2027-default-rtdb.firebaseio.com',
    storageBucket: 'camiones-2027.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEu8VgoUngcxzQSR6IvtiKG15g2RZUlsQ',
    appId: '1:825243621147:web:c7ed1045f1457a76b125be',
    messagingSenderId: '825243621147',
    projectId: 'camiones-2027',
    authDomain: 'camiones-2027.firebaseapp.com',
    databaseURL: 'https://camiones-2027-default-rtdb.firebaseio.com',
    storageBucket: 'camiones-2027.firebasestorage.app',
    measurementId: 'G-D2CDP79Q6L',
  );
}
